[package]
name = "measure_units_derive_internal"
version = "0.1.3"
edition = "2018"

[dependencies]
util = { path = "../../util" }

syn = { version = "~1.0", features = ["full"] }
proc-macro2 = "~1.0"
quote = "~1.0"
darling = "~0.13"
