[package]
name = "measure_units"
version = "0.1.3"
edition = "2018"

[dependencies]
util = { path = "../../util" }
measure_units_derive = { path = "../derive" }

num-traits = "~0.2"
num-derive = "~0.3"
derive_more = "~0.99"
