[package]
name = "measure_units"
version = "0.1.4"
edition = "2021"

[dependencies]
util = { path = "../../util" }
measure_units_derive = { path = "../derive" }

num-traits = "~0.2"
num-derive = "~0.3"
derive_more = "~0.99"

[dev-dependencies]
approx = "~0.5"
